service: work-orders-sns-filtering
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: WorkOrdersTable
    SNS_TOPIC_ARN: { "Ref": "WorkOrdersSNSTopic" }
    SQS_RECEIVED: { "Ref": "ReceivedQueue" }
    SQS_IN_PROGRESS: { "Ref": "InProgressQueue" }
    SQS_COMPLETED: { "Ref": "CompletedQueue" }
    SQS_CANCELED: { "Ref": "CanceledQueue" }

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: 
        - arn:aws:sns:us-east-1:*:work-orders-topic
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - arn:aws:sqs:us-east-1:*:work-orders-received
        - arn:aws:sqs:us-east-1:*:work-orders-in-progress
        - arn:aws:sqs:us-east-1:*:work-orders-completed
        - arn:aws:sqs:us-east-1:*:work-orders-canceled
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: 
        - arn:aws:dynamodb:us-east-1:*:table/WorkOrdersTable

functions:
  api:
    handler: src/api_handler.lambda_handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: work-orders
          method: post
      - http:
          path: work-orders
          method: get

resources:
  Resources:
    WorkOrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WorkOrdersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"

    WorkOrdersSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: work-orders-topic

    ReceivedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: work-orders-received

    InProgressQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: work-orders-in-progress

    CompletedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: work-orders-completed

    CanceledQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: work-orders-canceled

    ReceivedQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref ReceivedQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: sqs:SendMessage
              Resource: !GetAtt ReceivedQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref WorkOrdersSNSTopic

    InProgressQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref InProgressQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: sqs:SendMessage
              Resource: !GetAtt InProgressQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref WorkOrdersSNSTopic

    CompletedQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref CompletedQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: sqs:SendMessage
              Resource: !GetAtt CompletedQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref WorkOrdersSNSTopic

    CanceledQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref CanceledQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: sqs:SendMessage
              Resource: !GetAtt CanceledQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: !Ref WorkOrdersSNSTopic

    ReceivedQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref WorkOrdersSNSTopic
        Protocol: sqs
        Endpoint: !GetAtt ReceivedQueue.Arn
        FilterPolicy: 
          status: ["received"]

    InProgressQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref WorkOrdersSNSTopic
        Protocol: sqs
        Endpoint: !GetAtt InProgressQueue.Arn
        FilterPolicy: 
          status: ["in_progress"]

    CompletedQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref WorkOrdersSNSTopic
        Protocol: sqs
        Endpoint: !GetAtt CompletedQueue.Arn
        FilterPolicy: 
          status: ["completed"]

    CanceledQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref WorkOrdersSNSTopic
        Protocol: sqs
        Endpoint: !GetAtt CanceledQueue.Arn
        FilterPolicy: 
          status: ["canceled"]
